### ISSUE TITLE
Drop support for `pilot.eessi-hpc.org`

### ISSUE THREAD

**Issue by ocaisa** [EESSI/eessi-demo#36]
Recent PRs have included support for the pilot repo but we have a PR open to deprecate the pilot so there's really no good reason to do that.

If support for the pilot is really seen as interesting, we should just cut a release based on an old commit and consign it to history.

**Comment by boegel** [comment]
I agree, once all demo scripts have support for using `software.eessi.io` (we're close, only OpenFOAM left), we can create a `pilot.eessi-hpc.org` branch, and then clean up the script to assume `software.eessi.io` is used.

Maybe they should even do the `source` part as well, to make that clear?

**Comment by boegel** [comment]
@ocaisa This is ready to close thanks to #37 and the `pilot.eessi-hpc.org` branch being in place now?
