### ISSUE TITLE
update install scripts to CernVM-FS 2.8.0

### ISSUE THREAD

**Issue by boegel** [EESSI/eessi-demo#4]

**Comment by boegel** [comment]
@bedroge Do we need to update Stratum 0 and Stratum 1's to CernVM-FS 2.8.0 first?

**Comment by bedroge** [comment]
https://cvmfs.readthedocs.io/en/2.2/cpt-releasenotes.html#semantic-versioning
So, should be fine to use newer clients with older servers or vice versa.

**Comment by bedroge** [comment]
This was done in https://github.com/EESSI/eessi-demo/pull/9.
